### ISSUE TITLE
Support comments, line or block with the AutoLISP DCL filetype

### ISSUE THREAD

**Issue by nigma456** [Autodesk-AutoCAD/AutoLispExt#10]
This feature request is from the vscode extension market comment by Rina.

Comments, line or block, are not set up properly with the AutoLISPDCL filetype. Can this be added?
By Rina Yarmak 5/28/2020

**Comment by Rina-Y** [comment]
Oh hey! Its my request! I hope this gets put in! I almost thought about making an attempt at putting it in myself, but I know almost nothing about making vscode extensions or at least, how to actually do the edit/testing bits that isn't going into the extension I've downloaded and bodging something in.  

Thanks for transferring this over from the other place!

**Comment by LanDong-adsk** [comment]
fixed in V1.4.0
