### ISSUE TITLE
Please consider to move off deprecated VS Code APIs

### ISSUE THREAD

**Issue by weinand** [Autodesk-AutoCAD/AutoLispExt#11]
Hi, I'm @weinand from the VS Code team.

While investigating which debugger extensions are using deprecated extension API I found an issue with your extension (for details see https://github.com/microsoft/vscode/issues/88849).

In the package.json the deprecated contribution point "debuggers.adapterExecutableCommand" is used.

Please use the "vscode.DebugAdapterDescriptorFactory" and a "vscode.DebugAdapterExecutable" instead like shown [here](https://github.com/microsoft/vscode-mock-debug/blob/28b4fde41228b0aabe93eab9064992e276859405/src/extension.ts#L91-L116) with Mock debug.

You can register the adapter factory in the extensions "activate" function like this:
```js  
context.subscriptions.push(vscode.debug.registerDebugAdapterDescriptorFactory(DEBUG_TYPE, factory));
```

**Comment by whlkw** [comment]
Thanks for pointing out this!

**Comment by weinand** [comment]
@whlkw great, thanks!
