### ISSUE TITLE
Question: AutoLispDebugAdapter not found

### ISSUE THREAD

**Issue by WildOrangutan** [Autodesk-AutoCAD/AutoLispExt#129]
Hey, I'm getting error below. I can't find any information online, how to fix it. My autocad path and process are set correctly.

I'm using version Autocad 2020. How do I know which versions supports this adapter?

> AutoLispDebugAdapter.exe doesn’t exist. Verify that the file exists in the same folder as that for the product specified in the launch.json file.

**Comment by nigma456** [comment]
We support the vscode extension debugger since AutoCAD 2021. You can check the sysvar lispsys. If it is available then it should support the vscode debugger.

**Comment by LanDong-adsk** [comment]
@Sen-real , can we update the error message to indicate it only works after 2021?

**Comment by Sen-real** [comment]
@LanDong-adsk 
good idea

**Comment by Sen-real** [comment]
Close this issue. Solved in PR129.

**Comment by vargekt** [comment]
well, 2025 and still no update in that error message to show 2021 or higher requirement, nice work guys/girls.....and what's funny, from 2021 u can't permanently buy acad, just a subscription, what a coincidence...
