### ISSUE TITLE
I want to access help for a standard AutoLISP function

### ISSUE THREAD

**Issue by ambrosl-adsk** [Autodesk-AutoCAD/AutoLispExt#15]
In the context of editing a LSP file, I want to select a function name and then right-click and choose a command like Help from the right-click menu.  This should open the latest version of the AutoLISP Reference documentation in a Web browser to the selected function's topic, if no text is selected it could just open Help to a general or Homepage page.

**Comment by hansWurst-creator** [comment]
An additional option would be to include that information in the language server.

This extension shows what can easily be accomplished:
![image](https://user-images.githubusercontent.com/70693364/92107109-8b627280-ede5-11ea-97d5-f3a62e83817e.png)
[https://github.com/1833183060/autolisp](https://github.com/1833183060/autolisp)

A link to the corresponding help Article would be nice here as well.

**Comment by JD-Howard** [comment]
> 
> 
> I want to select a function name and then right-click and choose a command like Help from the right-click menu. This should open the latest version of the AutoLISP Reference documentation in a Web browser to the selected function's topic, if no text is selected it could just open Help to a general or Homepage page.

Its still a little raw right now and I had to touch more things than I would of expected, but I do have this exact functionality working on my local copy. Just waiting to hear back on my _Individual Contributor Agreement_.

**Comment by serhanbakir** [comment]
F1 key used to open up the online/offline help page about the selected function. Similar functionality will be very useful.

**Comment by JD-Howard** [comment]
> 
> 
> F1 key used to open up the online/offline help page about the selected function. Similar functionality will be very useful.

Thank you for the feedback. That was my original intent too, but that simply won't happen because F1 is a very integral default key binding set to activating the All-Commands bar. The more you use VSCode the more you'll come to realize just how valuable that default binding is.

**Comment by LanDong-adsk** [comment]
added "open online help" in V 1.4.0
