### ISSUE TITLE
Fail to go to definition on Mac unless open the lsp file

### ISSUE THREAD

**Issue by YitingTang-91** [Autodesk-AutoCAD/AutoLispExt#154]
**Describe the bug**
Mac Only. Fail to go to definition unless open the lsp file with definition of function. 
**To Reproduce**
1.  Open folder in vscode. The folder includes a/a.lsp and b/b.lsp.
2. a.lsp defines function foo(), b.lsp invokes function (foo)
3. Ensure a.lsp is not opened in vscode

**Expected behavior**
(foo) in b.lsp could goto (defun foo) in a.lsp

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Version 1.4

**Additional context**

**Comment by JD-Howard** [comment]
Confirming that PR #167 resolves this. Here is a screenshot of what my interpretation of the issue stated would cause the problem, but with #167 loaded, I get t
he expected jump.
![Screen Shot 2021-09-21 at 4 48 36 PM](https://user-images.githubusercontent.com/51800232/134262331-9c3945dc-a7c9-42d4-81eb-f1b20ade8bf5.png)
