### ISSUE TITLE
fail to  Go to definition  .

### ISSUE THREAD

**Issue by aeo000000** [Autodesk-AutoCAD/AutoLispExt#159]
I located this error from almost 10,000 lines of code。delete and delete ......

![image](https://user-images.githubusercontent.com/16606678/124161628-36a88a80-dad0-11eb-8722-50eb7609800d.png)

on 'savevar'  push F12.
This is the problem ？
    
![image](https://user-images.githubusercontent.com/16606678/124163949-bfc0c100-dad2-11eb-8dab-952a772c639c.png)

[test0.zip](https://github.com/Autodesk-AutoCAD/AutoLispExt/files/6749799/test0.zip)

**Comment by Sen-real** [comment]
thanks a lot for finding out this problem!

**Comment by Sen-real** [comment]
Solved as part of https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/160
