### ISSUE TITLE
Error: This instance of AutoCAD is currently being used to debug another file

### ISSUE THREAD

**Issue by crigNibhinn** [Autodesk-AutoCAD/AutoLispExt#164]
**Describe the bug**
Can't attach the Visual Code AutoLISP debugger to AutoCAD. Always reports that AutoCAD is in use. Won't even attach when trying to launch AutoCAD through Visual Code. I've followed every instruction I could but cannot get past this.

Tested with AutoCAD 2022 and 2021.
Tried a fresh install of Visual Code and AutoCAD
Tried re-install the plugin/extension
Tried restarting my PC

Maybe I'm just missing something obvious or I'm doing something wrong but I didn't have any luck with Autodesk support or online from searches. 

**To Reproduce**
1. Launch AutoCAD
2. Open Visual Code
3. Try to attach debugger or run debugging

**Expected behavior**
Debugger attaches and I can start loading LISP files using Visual Code, if my understanding of how it works is correct

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

**Comment by Sen-real** [comment]
@crigNibhinn 
would you please upload a snapshot which contains the error message? thanks a lot!

**Comment by crigNibhinn** [comment]
I actually managed to resolve the issue last night. I tested AutoCAD and Visual Code on a VM and it worked so it must have been any issue with my Windows install or an installed program causing issues. I ended up re-installing my OS and now it works perfectly.
