### ISSUE TITLE
yarn install - No Access to "art-bobcat.autodesk.com"

### ISSUE THREAD

**Issue by JD-Howard** [Autodesk-AutoCAD/AutoLispExt#17]
**Describe the bug**
I was going to download this and tinker with this a bit and apparently can't because the **art-bobcat.autodesk.com** domain is gone or down. Here is the output from my attempt to run _yarn install_

PS Z:\AutoLispExt> yarn install
yarn install v1.22.5
[1/5] Validating package.json...
warning autolispext@1.3.0: The engine "vscode" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://art-bobcat.autodesk.com:443/artifactory/api/npm/team-autocad-npm-virtual/cross-spawn/-/cross-spawn-5.1.0.tgz: getaddrinfo ENOTFOUND art-bobcat.autodesk.com".   
info If you think this is a bug, please open a bug report with the information provided in "Z:\\AutoLispExt\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Desktop (please complete the following information):**
Windows10

**Other**
I previously had NPM v6.14.4 & NODE v12.18.0 installed.
If you want my log file I can get it to you, but it seems pretty clear whats going on here.

**Comment by JD-Howard** [comment]
I am not quite sure what Autodesk is doing, that art-bobcat sub-domain shows up all over their web technology (Forge and such) platforms, but I have found a temporary work around if anyone else wants to tinker too. 

Open the yarn.lock and do search and replace on all these:
https://art-bobcat.autodesk.com:443/artifactory/api/npm/team-autocad-npm-virtual
Replace with:
https://registry.npmjs.org

Note: there is one radical that isn't quite that search field, so do a secondary search for art-bobcat to find it.

**Comment by hualin-adsk** [comment]
Thank you for pointing out this workaround!
And we are fixing the issue, preparing a Pull Request for this issue.

**Comment by JD-Howard** [comment]
I was about to submit the PR for enhancement #15 and decided to re-pull a fresh copy from git I hadn't been tinkering around with for those changes. Everything hooked up perfectly this time around.
