### ISSUE TITLE
Errors on the AutoCAD AutoLISP Extension for Visual Studio Code

### ISSUE THREAD

**Issue by roja83567** [Autodesk-AutoCAD/AutoLispExt#177]
Hello,

I installed VS Code, then its AutoCAD AutoLISP Extension (by Autodesk), in order to edit & debug my lisp programs. I was able to access this platform through plain AutoCAD 2021 via the VLISP command.

Also, I am following the steps from the Autodesk article below to configure & use properly VS Code & its extension to work with lisp programs for AutoCAD

-Getting Started with Visual Studio Code (AutoLISP/VS Code):
https://help.autodesk.com/view/OARX/2022/ENU/?guid=GUID-7BE00235-5D40-4789-9E34-D57685E83875

That being said, I got stuck on step 4, i.e. Create or Open an Existing AutoLISP Project. As shown on the attached JPG file, every time I click on the (a) "Create a New Project" icon or the (b) "Open an Existing Project" icon, I get the following errors respectively:

(a) command 'autolisp.createProject' not found
(b) command 'autolisp.openProject' not found

![Screenshot of the error](https://user-images.githubusercontent.com/101967550/159153877-bdf3987e-23ac-43e5-9f68-542e7fbef4b6.jpg)

I had tried to google these errors, but I did not found anything related to them.

Could you please advise?

Thanks in advance,
RR

**Comment by Sen-real** [comment]
Hi @roja83567 ,
I couldn't reproduce this problem. I guess the extension was not successfully installed on your machine.
Please have a try with following steps:
1. remove the AutoLISP extension;
2. restart VS Code
3. reinstall the AutoLISP extension; it may take sometime, so please wait until it's really finished, as shown below:
![image](https://user-images.githubusercontent.com/57521938/159239734-2006664f-26fe-41a2-8b11-acead60b6742.png)

Hope it works this time.

**Comment by roja83567** [comment]
Hi @Sen-real ,

Thanks for your input on this matter.

I tried your suggestion unsuccessfully; however, I updated both VS Code & the AC AutoLISP Extension to the next available versions, v1.65.2 & v1.5.0 respectively, and the problem was solved.

Thanks again for igniting the spark that helped to resolve the cause of this issue.

Cheers,
RR

**Comment by Sen-real** [comment]
Hi @roja83567 ,
Really happy to know it works now!
Yes, since VS Code APIs keep changing/upgrading, please make sure your VS Code and AutoLISP Extension are upgraded to the latest versions. 
Can we resolve this issue?

**Comment by roja83567** [comment]
Thanks @Sen-real ,

The issue has already been resolved, so it's all good now.

Cheers,
RR
