### ISSUE TITLE
After Ctrl + K + 0 to collapse, cannot expand all by Ctrl + K + 9

### ISSUE THREAD

**Issue by hawston** [Autodesk-AutoCAD/AutoLispExt#18]
I use Ctrl + K + 0 to collapse all sections, but after that I cannot expand all by Ctrl + K + 9..

**Comment by nigma456** [comment]
According to the vscode document the expand should be Ctrl + K + J.
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by hualin-adsk** [comment]
@hawston If you agree, I will ask to close the issue.

**Comment by hawston** [comment]
Yes. Can close
