### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by deltco84** [Autodesk-AutoCAD/AutoLispExt#180]
- Issue Type: `Performance`
- Extension Name: `autolispext`
- Extension Version: `1.5.0`
- OS Version: `Linux x64 5.16.0-kali7-amd64`
- VS Code version: `1.56.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/Autodesk.autolispext-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nigma456** [comment]
Thank you to report this and we will take a look.

**Comment by nigma456** [comment]
Thank you to report this and we will take a look.

**Comment by Sen-real** [comment]
Hi @deltco84 , the extension is designed for Autocad Windows & Mac. Linux is not yet supported.
See https://marketplace.visualstudio.com/items?itemName=Autodesk.autolispext.

**Comment by Sen-real** [comment]
I'm closing this issue as it's not yet supported. Please let me know if there's anything else in problem.
