### ISSUE TITLE
Missing 2023 Target Year

### ISSUE THREAD

**Issue by Rina-Y** [Autodesk-AutoCAD/AutoLispExt#193]
Just hoping to get the extension to include the current version of AutoCAD.  (It has been months since AutoCAD was updated to 2023, and it isn't an option for the extension access help from).

**Comment by Sen-real** [comment]
Thanks a lot, I'm updating the code...

**Comment by Sen-real** [comment]
Fixed by https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/194, and will be included in 1.5.1
