### ISSUE TITLE
Regular Expression code not executed properly

### ISSUE THREAD

**Issue by jtoverka** [Autodesk-AutoCAD/AutoLispExt#219]
**Describe the bug**
VBScript.RegExp COM object does not execute code properly when LISPSYS system variable is 1 or 2 (required to use Visual Studio Code extension)

**To Reproduce**
Have AutoCAD 2021 or newer.
(To "run code below", copy and paste entire code into AutoCAD command line.)
- LISPSYS variable of 1 or 2
- Restart AutoCAD for changes to take effect
- Run code below
- A dialog box will show "Failed" for incorrect code execution.
- LISPSYS variable of 0
- Restart AutoCAD for changes to take effect
- Run code below
- A dialog box will show "Passed" for correct code execution.
```
((lambda ( / _RegExExecute)
  ;; Clips from Lee Mac BFIND v2.0
  ;; http://www.lee-mac.com/bfind.html
  (or (vl-bb-ref '*REX*)
    (vl-bb-set '*REX* (vlax-create-object "VBScript.RegExp")))
  (defun _RegExExecute ( pat string case / lst )
    (vlax-put    (vl-bb-ref '*REX*) 'Pattern pat)
    (vlax-put    (vl-bb-ref '*REX*) 'Global actrue)
    (vlax-put    (vl-bb-ref '*REX*) 'IgnoreCase (if case acfalse actrue))
    (vlax-for x  (vlax-invoke (vl-bb-ref '*REX*) 'Execute string)
      (setq lst
        (cons (list (vlax-get x 'Value) (vlax-get x 'FirstIndex)) lst)
      )
    )
    lst
  )
  (if
    (_regExexecute
      (strcat "0" (chr 208)(chr 42) "8" (chr 208)(chr 42) "1" (chr 208)(chr 42)) ;; "081" after transformation
      "081618.21"
      t
    )
    ;; ACADE 2020 or older result: '(("081" . 0))
    ;; ACADE 2021 or newer LISPSYS value 0: '(("081" . 0))
    ;; ACADE 2021 or newer LISPSYS value 1 or 2: nil
    (alert "Passed")
    (alert "Failed")
  )
  (princ)
))
```

**Expected behavior**
Expected:
ACADE 2020 or older result: '(("081" . 0))
ACADE 2021 LISPSYS value 0: '(("081" . 0))
Test Program Output: "Passed"

Unexpected:
ACADE 2021 LISPSYS value 1 or 2: nil
Test Program Output: "Failed"

**Screenshots**
N/A

**Desktop:**
 - OS: Windows 10 Enterprise
 - Version: 22H2
 - OS build: 19045.2486
 - Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz
 - 32 GB RAM

**Additional context**
Clips of this code is provided by [Lee Mac](http://www.lee-mac.com/bfind.html)
Information on [LISPSYS](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/AutoCAD-Core/files/GUID-1853092D-6E6D-4A06-8956-AD2C3DF203A3-htm.html)
I have ran the code provided above in AutoCAD Electrical 2018 and AutoCAD Electrical 2021.

**Comment by Sen-real** [comment]
Hi @jtoverka , thanks for logging this issue.
I reproduced the problem on ACAD 2021, but it seems fixed already on newer versions of ACAD (2022+).
Would you please have a try?

**Comment by Sen-real** [comment]
@jtoverka 
I'm closing this issue as it has been fixed in newer versions of ACAD.
Please let me know if I'm missing anything.
