### ISSUE TITLE
Run a selection of code

### ISSUE THREAD

**Issue by stephen147** [Autodesk-AutoCAD/AutoLispExt#232]
Instead of running the entire file. Allowing a selection of code to be run would be very useful.

**Comment by Sen-real** [comment]
Good point, thanks for the suggestion!

**Comment by kdub-nz** [comment]
Yes, evaluating a selection would be really productive.
Would this be possible.

**Comment by kdub-nz** [comment]
Ignore my previous, It appears that
Rt-click on selected statements brings up the menu that has 
'Evaluate in Debug Console ' available.

**Comment by stephen147** [comment]
> 'Evaluate in Debug Console ' available.

Cool, I have now mapped that to a keyboard shortcut.

I'll let the admins close this request but for me, this is what I was after.
