### ISSUE TITLE
Review selection set contents

### ISSUE THREAD

**Issue by aspect-ex** [Autodesk-AutoCAD/AutoLispExt#234]
Hi all.

In Visual Lisp, double-clicking the return value of ssget will list the contents of the selection set. Can you see this in the AutoLisp Extension?

Thank you.

**Comment by Sen-real** [comment]
Hi @aspect-ex , it seems the same limitation mentioned in https://github.com/Autodesk-AutoCAD/AutoLispExt/issues/188, so let's track this issue there. 
Please correct me if I misunderstand the problem.
