### ISSUE TITLE
Help: Target Year 2025

### ISSUE THREAD

**Issue by EnM4st3r** [Autodesk-AutoCAD/AutoLispExt#249]
Hi, can the Help Target Year for 2025 be added?

In settings:
![image](https://github.com/Autodesk-AutoCAD/AutoLispExt/assets/163658977/2a130811-2264-40b4-9bb5-edea4bc3bb2a)

**Comment by Sen-real** [comment]
Thanks, @EnM4st3r , I'll make an update on this soon.
I'm also thinking if there's a better way that can avoid making an update every year on this field ...
