### ISSUE TITLE
Update Project to TypeScript 3.7

### ISSUE THREAD

**Issue by JD-Howard** [Autodesk-AutoCAD/AutoLispExt#31]
**Is your feature request related to a problem? Please describe.**
We are missing a major bit of functionality (null chaining) that would clean up our logical expressions.

The following throws an error in TS when trying to transpile to JS:
```typescript
if (vscode.window.activeTextEditor?.document)
````

**Describe the solution you'd like**
Update to TypeScript 3.7.0 or greater. This null chaining is [native to JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and TypeScript finally got around to supporting it. Our conditionals would really benefit (more concise) from this update.

**Additional context**
Here is the release notes about chaining.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

I played around with doing this, but I think NodeJs (and maybe more) also needs to be updated in order to use 3.7

**Comment by LanDong-adsk** [comment]
updated in v 1.4.0
