### ISSUE TITLE
Cannot open project file

### ISSUE THREAD

**Issue by morbius1st** [Autodesk-AutoCAD/AutoLispExt#36]
**Describe the bug**
Open an existing project fails with the message that the project file is malformed.

**To Reproduce**
1.  create a project
2. add files to project
3. close project (open something else)
4. goto AutoLisp project sidebar
5. chose open existng project
6. select the project just made above
7. project does not open and dialog box is displayed that reads "failed to open the specified project.  Error: Malformed project file ..."

**Expected behavior**
Project file is opened and project list is updated

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10.0.10941

**Additional context**
none

**Comment by JD-Howard** [comment]
Jeff, 
Unfortunately that error is a somewhat generalized response to a failure of parsing as a whole and doesn't tell me much about why. If you attach the *.PRJ file your having issues with, I'd be happy to run it through the debugger and narrow down the why for you.

**Comment by hualin-adsk** [comment]
And I also can not repro the issue to follow your steps!

**Comment by morbius1st** [comment]
A PRJ file is attached.

I assume that you followed the procedure noted and it worked - yes?

Attached is a pic of the error message when I try to open the file.

[Start System.zip](https://github.com/Autodesk-AutoCAD/AutoLispExt/files/5443083/Start.System.zip)
![image](https://user-images.githubusercontent.com/17919240/97259637-82d05c00-17d8-11eb-8be2-f46677c362b5.png)

**Comment by JD-Howard** [comment]
Thank you Jeff, I see the problem. 
It looks like PRJ names are not compatible with spaces, but our extensions PRJ interface lets you create them with spaces. To fix that file you'll have to change "Start System" to "StartSystem" and open up the file in a text editor to put StartSystem together on one line too.

**Comment by morbius1st** [comment]
That fixed it - thanks.  Should be an easy fix in the code.
