### ISSUE TITLE
Allow non-AutoLisp files in the project list.

### ISSUE THREAD

**Issue by morbius1st** [Autodesk-AutoCAD/AutoLispExt#40]
**Is your feature request related to a problem? Please describe.**
I work with more than just AutoLisp files for my project.  I use text files and .dat files but these are not permitted in the project list.

**Describe the solution you'd like**
1.  Allow the addition of any file in the project list.  
2.  provide a setting that provides a list of extensions to never add to the file list (e.g. .EXE files or .DLL files, etc.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by hualin-adsk** [comment]
it looks like old VLIDE project can not include other type files. To keep the back compatibility, it looks like we can not support this.
Maybe it needs to communicate widely if we decide to bring this feature.

**Comment by JD-Howard** [comment]
It is not possible to support this and reverse compatibility. This needs to be closed.

**Comment by rtogores** [comment]
Workspaces can include files of any kind. So why use projects?

**Comment by hualin-adsk** [comment]
Autolisp has tons of legacy codes, and the old VLIDE command supports the projects file (to imagine that in real world users have hundreds of lisp files in different folders), it can be managed via PROJECT feature in old AutoCAD or vscode extension.

So there are two ways to work on AutoLisp in vscode:
1. Use workspace. I think this is more vscode flavor.
2. Use projects. This is legacy AutoCAD flavor.

**Comment by hualin-adsk** [comment]
@LanDong-adsk This is as design, so I think it can be closed
