### ISSUE TITLE
Contextual menu item to add file to project

### ISSUE THREAD

**Issue by Rina-Y** [Autodesk-AutoCAD/AutoLispExt#47]
I'm just getting started trying out the .prj feature, I never used VLIDE for the lisp system I manage so I had never ran across it before.  There are hundreds of files in my lisp system and am trying to cherry pick specific files into subject related projects to try it out.  

The first thing I attempted when trying to add specific files to the project was right-click on the file in the workspace explorer and look for an item "Add to Current AutoLISP Project", hoping it was there.  Well, second thing, because the first thing was the "Add File to Project" button in the AutoLISP Project Manager area and added one manually that way.  I realized how much of a pain it would be to do this for the next 50 or so files, so I immediately *hoped* that there would be a contextual menu option for me to add things easily to the project.

**Comment by hualin-adsk** [comment]
Maybe another solution is to support adding a folder to the project (automatically to add all the files in that folder to project).

**Comment by JD-Howard** [comment]
I could be wrong, but I wouldn't think it would be very difficult to hook up a workspace "Add file to project" context menu item.

**Comment by JD-Howard** [comment]
This has been implemented on the pending PR #51 
**When** the PR gets merged, the system is configured to auto-generate a [pre-release](https://github.com/Autodesk-AutoCAD/AutoLispExt/releases) installer. You could (if you want) download that and a VSCode extension that is designed to install *.vsix files if you want to beta test it; just don't expect documentation on pre-release features...

**Comment by rtogores** [comment]
> 
> 
> Maybe another solution is to support adding a folder to the project (automatically to add all the files in that folder to project).

This is just as the Workspace feature works... Try the FILE > ADD FOLDER TO WORKSPACE menu option.

**Comment by hualin-adsk** [comment]
@LanDong-adsk Or maybe this issue can be closed

**Comment by LanDong-adsk** [comment]
The IDE supports multi-selection so it should be easy to add multiple files into the project.
