### ISSUE TITLE
textmate scopes Problem with T

### ISSUE THREAD

**Issue by hansWurst-creator** [Autodesk-AutoCAD/AutoLispExt#48]
**Describe the bug**
Nil is properly recognized as a constant and properly color coded. Sadly T is not

**To Reproduce**
![image](https://user-images.githubusercontent.com/70693364/98938038-97eeff80-24e7-11eb-95ab-4ccbad62d558.png)
![image](https://user-images.githubusercontent.com/70693364/98938445-2d8a8f00-24e8-11eb-84ae-d7847250fc7c.png)

**Expected behavior**
T should also be recognized as a Constant like nil

Sorry for the confusion. Upon further inspection it seems like the scope is coming from [[https://marketplace.visualstudio.com/items?itemName=niaoge.autolisp]](https://marketplace.visualstudio.com/items?itemName=niaoge.autolisp)

It would still be nice to have it properly recognized by this extension as well though.

**Comment by hualin-adsk** [comment]
I see this in our extension:
<img width="332" alt="Screen Shot 2020-11-21 at 9 09 15 AM" src="https://user-images.githubusercontent.com/68938334/99863483-5a6e2e80-2bd9-11eb-89d5-5e260f35f880.png">

Do you mean that we should syntax highlight the `NIL and nil`?

**Comment by hansWurst-creator** [comment]
Seems like nil is not recognized as a keyword:
![image](https://user-images.githubusercontent.com/70693364/99968566-918b3e00-2d99-11eb-9002-6568278ba4b4.png)![image](https://user-images.githubusercontent.com/70693364/99968825-f181e480-2d99-11eb-8730-296a8e147c96.png)

I use this vscode command to look at what is going on:
![image](https://user-images.githubusercontent.com/70693364/99968934-1a09de80-2d9a-11eb-9148-cc4e4e8f34f0.png)

**Comment by hualin-adsk** [comment]
I think this commit https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/71 can resolve the issue.

**Comment by LanDong-adsk** [comment]
fixed in V1.4.0
