### ISSUE TITLE
I want to close a project on project panel.

### ISSUE THREAD

**Issue by Sen-real** [Autodesk-AutoCAD/AutoLispExt#5]
**Is your feature request related to a problem? Please describe.**
Close Project, this doesn’t seem to be possible in the current flow. 

**Describe the solution you'd like**
VLIDE allowed the user to this, and feels like I should be able to close something if I opened it.
We should be able to do it on the project panel.

**Describe alternatives you've considered**
No.

**Additional context**
From: Lee Ambrosius

**Comment by rtogores** [comment]
Use a Workspace instead. Then you have the Files > Close Workspace (CTRL+K F) menu option.
The Workspace toolbar includes the icons New File, New Folder, Refresh, and Collapse Folders in Explorer (as a Workspace displays the folders also).
And using a Workspace you will also have the Explorer contextual menu available and also the Explorer's TIMELINE section (supposing you are taking advantage of VS Code's Source Code Management feature installing GIT).

**Comment by Sen-real** [comment]
> Use a Workspace instead. Then you have the Files > Close Workspace (CTRL+K F) menu option.
> The Workspace toolbar includes the icons New File, New Folder, Refresh, and Collapse Folders in Explorer (as a Workspace displays the folders also).
> And using a Workspace you will also have the Explorer contextual menu available and also the Explorer's TIMELINE section (supposing you are taking advantage of VS Code's Source Code Management feature installing GIT).

@rtogores ,  please note that autolisp project is a feature which has been there for a couple of decades, we need a way to continue working with legacy project files. For new "project" from now on, working with workspace is also a good idea.

**Comment by szilvaa-adsk** [comment]
For more context for Workspace vs. project see #9.

**Comment by JD-Howard** [comment]
This should have been taken care of with PR #29

**Comment by szilvaa-adsk** [comment]
We'll close the issue once we have public release with this fix.

**Comment by LanDong-adsk** [comment]
fixed in v1.4.0
