### ISSUE TITLE
Problems with Debug Attach

### ISSUE THREAD

**Issue by hansWurst-creator** [Autodesk-AutoCAD/AutoLispExt#60]
Following the advise from @JD-Howard in https://github.com/Autodesk-AutoCAD/AutoLispExt/issues/57#issuecomment-744711613_  I can successfully get the Debug Launch to get working.

However using Debug attach throws the following error:
![image](https://user-images.githubusercontent.com/70693364/102491295-41d62480-4070-11eb-8323-0e8430bd86c8.png)

**Comment by LanDong-adsk** [comment]
did you use winCompile.bat to compile the code?

**Comment by LanDong-adsk** [comment]
@hansWurst-creator , do you still have problem with debug attach?

**Comment by hansWurst-creator** [comment]
hmm I tried it some time ago but gave up as I didn't get it to work. Is there a guide for how I can test the beta versions of this expansion? then I will try again.

**Comment by LanDong-adsk** [comment]
you can try 
`python pack.py` and then debug. See if it works.

**Comment by hansWurst-creator** [comment]
https://github.com/Autodesk-AutoCAD/AutoLispExt/releases/tag/v1.4.1-2d7759d789b8a3239fc32c487b0746112163b5da
using the latest release vsix seems to work fine

I just used the vscode command: 
![image](https://user-images.githubusercontent.com/70693364/109950599-fb8e7a00-7cdc-11eb-8d91-f2aebd96bbf5.png)
 to install the vsix and i am able to debug with it
