### ISSUE TITLE
I want to be able to configure the help link

### ISSUE THREAD

**Issue by LanDong-adsk** [Autodesk-AutoCAD/AutoLispExt#70]
**Is your feature request related to a problem? Please describe.**
when I click Open Online Help, I want to be directed to the help page with same version as my AutoCAD's.

**Describe the solution you'd like**
I want to be able to configure the online help link so that I can change as needed.

**Comment by JD-Howard** [comment]
>Same version as my AutoCAD

Where do you propose this information to comes from? Are we talking:
- New user setting?
- QuickPickItem question asked once per session?
- Mandating a launch value be configured and parsing out the year?
- Using the AcadProcessFinder? (this might be windows only, but I am not sure) 

I would also point out the recent change that imbedded the year at the time the JSON data file was generated, did add a large degree of bullet proofing around Autodesk's web team changing the GUID's on us. This enhancement would mitigate that security blanket.

**Comment by hualin-adsk** [comment]
After we discussed with testers and user experiences assistant, we thought that the extension can be used in old AutoCAD like AutoCAD2021, user MAY want to access the corresponding help page instead of the current year or hard code year.
So we created this issue here, and plan to hear feedback from users after released this version extension.

**Comment by hansWurst-creator** [comment]
I would like it to be automatically configured if the setting "autolispext.debug.LaunchProgram" is set.
A once per session question gets annoying very fast.
A user setting would probably be the easiest to implement and should work fine for now.

**Comment by Sen-real** [comment]
Resolved in AutoLISP extension v1.5.0
