### ISSUE TITLE
Search Path for go to definition

### ISSUE THREAD

**Issue by hansWurst-creator** [Autodesk-AutoCAD/AutoLispExt#86]
While testing out the great go to definition feature, I noticed, that it also seems to be searching through the .vscode folder in my workspace. Is there any way to change which locations are searched for the go to definition feature?
![image](https://user-images.githubusercontent.com/70693364/108715844-a94e9b80-751b-11eb-841e-d8b3691cde14.png)

**Comment by hualin-adsk** [comment]
@JD-Howard In the current implementation there is no way to config which folders it should or should not search.

**Comment by JD-Howard** [comment]
I see your point, this folder should really be an exception. Here is current order of operations is:
- Try to find it in the known open documents (restored documents from previous session excluded until activated)
- If no definition found, then try the PRJ references
- If no definition found, then search every single LSP in the Workspace folder

**Comment by hansWurst-creator** [comment]
Is it possible that for your search you respect the vscode setting:
files.exclude

> Note; the descriptions above are specific to functions. Variables are 100% active document only. I have plenty of global variables holding special style and layer names. So, I would like to expand the variable system, but I don't think its viable unless we only support PRJ files or add some kind of JSDOC style annotations to identifiers for true interoperability variables. Possibly a minimum complexity requirement, but that just sounds hard to document/explain.

I think most people only have a couple of files with global variables. So maybe just a comment at the top of the file is enough? So you could search through those files, besides the active document, as well for global variables.

**Comment by JD-Howard** [comment]
I think the files.exclude is an excellent idea, but I do think there needs to be some kind of initial-blocking mechanism too; maybe even a reminder when the extension first initializes. So, we would probably need to add an AutoLispExt setting that must be explicitly turned on for allowing generalized global variable extraction. This probably wouldn't add any meaningful overhead from what we are already doing as long as we restrict it to top-level (setq) statements. The second we have to dig through every function and check for non-localization the workspace parse will take a large performance hit.

I am all for adding behavioral and documentation commenting to this Extension. Some version of JSDOC is coming to this even if it only exists in a personal use fork... lol

**Comment by Sen-real** [comment]
The [improvement](https://github.com/Autodesk-AutoCAD/AutoLispExt/pull/126) is now in AutoLISP extension v1.5.0.
