### ISSUE TITLE
different auto format between foreach and vlax-for

### ISSUE THREAD

**Issue by hansWurst-creator** [Autodesk-AutoCAD/AutoLispExt#90]
Currently the autoformating of foreach and vlax-for is creating the following result:
![image](https://user-images.githubusercontent.com/70693364/108996409-9f08da80-769e-11eb-90d9-a0667af5c15e.png)
Something that is bothering me, is that the foreach and vlax-for look differently with auto format. With foreach first the iteration symbol and then the list through which is iterated are all put in one line. This is also the same syntax you see in many other languages (eg. vba, c# etc.). With vlax-for the collection is put on a separate line.
This makes it a bit harder to understand what is going on in my opinion.

I would prefer if autoformating would have this result:
![image](https://user-images.githubusercontent.com/70693364/108997635-1f7c0b00-76a0-11eb-9ddc-4b57b6d17ded.png)

**Comment by Sen-real** [comment]
@hansWurst-creator :
do you mean to provide auto-formatting like this?
![image](https://user-images.githubusercontent.com/57521938/109292890-03c26180-7866-11eb-9d3f-a4001504f230.png)

**Comment by hansWurst-creator** [comment]
yeah sorry that is what I meant. Hmm I must have copied the wrong picture.

**Comment by JD-Howard** [comment]
I can fix this when Parsing & Formatting get abstracted away from each other. I tested changing:
https://github.com/Autodesk-AutoCAD/AutoLispExt/blob/2d7759d789b8a3239fc32c487b0746112163b5da/extension/src/format/sexpression.ts#L844
into
`else if (opName == "foreach" || opName == "vlax-for") {`
seems to work fine

**Comment by hansWurst-creator** [comment]
this is fixed in Version 1.50
