### ISSUE TITLE
Wrong description in snippet.

### ISSUE THREAD

**Issue by rtogores** [Autodesk-AutoCAD/AutoLispExt#93]
**Describe the bug**
The description for the NTH snippet is wrong.
**Expected behavior**
The current description is "Evaluates each expression a specified number of times, and returns the value of the last expression" but it should be "Returns the nth element of a list".

**Comment by hualin-adsk** [comment]
Thanks for point out this!

**Comment by Sen-real** [comment]
Fixed in 1.5.0
